"""Aumenta tamanho da coluna password

Revision ID: 10acee76159a
Revises: 6902a0bc6b5b
Create Date: 2025-08-11 20:44:12.272799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10acee76159a'
down_revision = '6902a0bc6b5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
