"""Alterando done para completed

Revision ID: 6902a0bc6b5b
Revises: 3f6374b109f4
Create Date: 2025-08-09 16:32:12.743464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6902a0bc6b5b'
down_revision = '3f6374b109f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))
        batch_op.drop_column('done')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('done', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
